ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views

app_name='cart'
urlpatterns = [
    path('addtocart/<int:i>', views.addtocart,name='addtocart'),
    path('cart_view', views.cart_view,name='cart_view'),
    path('cart_remove/<int:i>', views.cart_remove,name='cart_remove'),
    path('cart_delete/<int:i>', views.cart_delete,name='cart_delete'),
    path('orderform', views.orderform,name='orderform'),
    path('payment_status/<U>', views.payment_status,name='payment_status'),
    path('order_view', views.order_view,name='order_view'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views

app_name='search'

urlpatterns = [
    path('', views.search_products,name='search_products'),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from shop import views
app_name='shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.categories,name="categories"),
    path('products/<int:p>', views.products,name="products"),
    path('productdetails/<int:p>', views.productsdetails,name="productdetails"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('addcategories', views.addcategories, name="addcategories"),
    path('addproducts', views.addproducts, name="addproducts"),
    path('addstock/<int:i>', views.addstock, name="addstock"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.

class Cart(models.Model): #cart table definition
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)


    def subtotal(self):
        return self.quantity*self.product.price



class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30)
    paid=models.BooleanField(default=False)



class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=30,blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Payment,Order_details
from django.contrib.auth.models import User

from django.views.decorators.csrf import csrf_exempt
from shop.models import Product

import razorpay

# Create your views here.
@login_required
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(product=p,user=u)
        if(p.stock>0):
            c.quantity+=1
            c.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock>0):
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock -= 1
            p.save()
    return redirect('cart:cart_view')


@login_required
def cart_view(request):
    u=request.user
    total = 0
    try:
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
    except:
        pass

    context={'cart':c,'total':total}
    return render(request,"cart.html",context)
@login_required
def cart_remove(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c = Cart.objects.get(product=p, user=u)
        if (c.quantity > 1):
            c.quantity -= 1
            c.save()
            p.stock += 1
            p.save()

        else:
            c.delete()
            p.stock += 1
            p.save()
    except:
        pass

    return redirect('cart:cart_view')

@login_required
def cart_delete(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c = Cart.objects.get(product=p, user=u) # check the product present in cart table for a particular user
        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass

    return redirect('cart:cart_view')


@login_required
def orderform(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['p']
        pin=request.POST['pi']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total1=int(total*100)


        client=razorpay.Client(auth=('rzp_test_HMYpZCzxKThslE','I3gnj3Rli50AavmgRkNgv6Zn')) #creates a cllient connection using razorpay id and secret code

        response_payment=client.order.create(dict(amount=total1,currency="INR"))# creates an order with razorpay using razorpay client
        print(response_payment)


        order_id=response_payment['id'] #retrieves the order_id from response
        status=response_payment['status'] #retrieves the status from response

        if(status == "created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone=phone,pin=pin,order_id=order_id)
                o.save()
        response_payment['name']=u.username
        context={'payment':response_payment}
        return render(request, "payment.html",context)
    return render(request,"orderform.html")




@csrf_exempt
def payment_status(request,u):

    if(request.method=="POST"):
        response=request.POST
        print(response)


        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
            }

        client=razorpay.Client(auth=('rzp_test_HMYpZCzxKThslE','I3gnj3Rli50AavmgRkNgv6Zn')) #to create a razorpay client
        print(client)

        try:

            status=client.utility.verify_payment_signature(param_dict) #To check the authenticity of the razorpay signature
            print(status)

            #to retrieve a particular record from payment table matching with razorpay response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id']
            p.paid=True
            p.save()


            #to retrieve a record from order_details table matching with razorpay response order id
            o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status="completed"
                i.save()


            u=User.objects.get(username=u)
            c=Cart.objects.filter(user=u)
            c.delete()


        except:
            pass

    return render(request, "payment_status.html")



@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    print(o)
    context={'orders':o}
    return render(request, "orderview.html",context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


def search_products(request):
    p = None
    query = ""
    if(request.method=="POST"):
        query=request.POST.get('q')
        if query:
            p=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query)) # filter the record matching with query
    context={'product':p,'query':query}
    return render(request,'search.html',context)

ecommerce/templates/addcategories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 mx-auto" style="margin-bottom:100px;">

    <form method="POST">

        <div class="mb-3">
            <label class="form-label">Name</label>
              <input type="text" class="form-control" name="n" placeholder="Enter your name">
            </div>

    <div class="mb-3">
  <label for="formFileSm" class="form-label">Image</label>
  <input class="form-control form-control-sm" id="formFileSm" type="file">
</div>

    <div class="mb-3">
    <label class="form-label">Description</label>
        <textarea class="form-control" name="d" placeholder="Write category description"></textarea>
    </div>




     <div class="mb-3">
<button type="submit" value="submit" class="form-control btn btn-outline-success">Submit</button>
  </div>
</form>
</div>
{% endblock %}

ecommerce/templates/addproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 mx-auto" style="margin-bottom:100px;">

    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Name</label>
              <input type="text" class="form-control" name="n" placeholder="Enter product name">
            </div>


        <div class="mb-3">
  <label for="formFileSm" class="form-label">Image</label>
  <input class="form-control form-control-sm" id="formFileSm" type="file">
</div>


    <div class="mb-3">
    <label class="form-label">Description</label>
        <textarea class="form-control" name="d" placeholder="Write category description"></textarea>
    </div>


        <div class="mb-3">
            <label class="form-label">Stock</label>
              <input type="text" class="form-control" name="s" placeholder="Enter stock">
            </div>

        <div class="mb-3">
            <label class="form-label">Price</label>
              <input type="text" class="form-control" name="p" placeholder="Enter price">
            </div>

        <div class="mb-3">
            <label class="form-label">Category</label>
            <select name="c">
                {% for i in links %}
                <option value="{{i.name}}">{{i.name}}</option>
                {% endfor %}
            </select>

            </div>

        <div class="mb-3">
            <button type="submit" value="submit" class="form-control btn btn-outline-success">Submit</button>
        </div>
</form>
    </div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-3 mx-auto" style="margin-bottom:100px;">
    <h2 class="mx-auto">Add stock details</h2>
    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label"></label>
              <input type="number" class="form-control" value="{{pro.stock}}" name="n" placeholder="Enter stock">
            </div>

        <div class="mb-3">
<button type="submit" value="submit" class="form-control btn btn-outline-success">Submit</button>
  </div>
</form>
</div>

{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
<!--    <div style="height:100px;width:100%"></div>-->
<div class="row">
    <h2 class="text-center fw-bold mb-5">Shopping Cart</h2>
    <div class="col-7">
    <table class="table table-bordered table-striped me-5">
        <tr>
            <th colspan="7" class="text-center">cart items</th>
        </tr>
        {% for i in cart %}
        <tr>
            <td class="p-3"><img src="{{i.product.image.url}}" height="100px"></td>
            <td class="text-center">Product: {{i.product.name}}</td>
            <td class="text-center">Price: {{i.product.price}}<br>
                Qty: {{i.quantity}} </td>
            <td class="text-center">Subtotal: {{i.subtotal}}</td>


            <td>
            {% if i.product.stock > 0 %}
            <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus text-dark"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
            <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash text-dark"></i></a>

            {% else %}
            <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus text-dark"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
            <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash text-dark"></i></a>

            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </table>
    </div>
        <div class="col-4">
    <table class="table table-bordered table-striped me-5">
        <tr>
        <th class="text-center">Check Out</th>
        </tr>
        <tr>
        <th class="text-center">Total Price {{total}}</th>
        </tr>
    </table>

    <div class="d-flex justify-content-between">
        <a href="{% url 'cart:orderform' %}" class="btn btn-outline-secondary ">Order Now</a>
        <a href="{% url 'cart:orderform' %}" class="btn btn-outline-secondary ">Continue Shopping</a>

    </div>
</div>
</div>
</div>




{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-2 mb-5">
<h2 class="text-center mt-3">Login</h2>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="password">
</div>
    <div class="mb-3">
<button type="submit" value="login" class="form-control btn btn-outline-success">Login</button>
  </div>
</form>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Address</label>
        <textarea class="form-control" name="a" placeholder="Enter your address"></textarea>
    </div>

    <div class="mb-3">
    <label class="form-label">Phone number</label>
      <input type="text" class="form-control" name="p" placeholder="Enter phone number">
    </div>

    <div class="mb-3">
    <label class="form-label">Pin number</label>
      <input type="text" class="form-control" name="pi" placeholder="Enter pin number">
    </div>
    <div class="mb-3">
<button type="submit" value="Register" class="form-control btn btn-outline-success">Submit</button>
  </div>
</form>
{% endblock%}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-5 p-3 mx-auto" style="margin-bottom:100px;">
<h2 class="mx-auto">order details</h2>

    {% for i in orders %}
    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Product Name: {{i.product.name}}</h5>
        <p class="card-text">Order total: {{i.product.price}}</p>
        <p class="card-text">Quantity: {{i.no_of_items}}</p>
        <p class="card-text">Ordered on: {{i.ordered_date}}</p>
        <p class="card-text">Order id: {{i.order_id}}</p>
        <p class="card-text">Delivery status id: {{i.product.delivery_status}}</p>
      </div>
    </div>
  </div>
  </div>
       {% endfor %}
</div>

{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px;">

<form action="{% url 'cart:payment_status' payment.name %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_HMYpZCzxKThslE" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.order_id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="KAI"
    data-description="shop smarter.shop here"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="kai@gmail.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    </div>

{% endblock %}

ecommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px:">
    <h2>payment status</h2>
    </div>


{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="latest-blog" class="py-5" style="background-image: url('{% static 'images/background-pattern.jpg' %}');background-repeat: no-repeat;background-size:cover;">

<div class="card mb-3 mx-auto my-3" style="max-width: 740px;">
  <div class="row g-0 ">
    <div class="col-md-4 my-5">
      <img src="{{pro.image.url}}" class="img-fluid rounded-start" alt="..." height="400px">
    </div>
    <div class="col-md-8">
      <div class="card-body m-3">
        <h5 class="card-title ">{{pro.name}}</h5>
        <h5 class="card-title"><i class="fa-solid fa-indian-rupee-sign"></i><i>{{pro.price}}</i></h5>
        <p class="card-text text-secondary">{{pro.description}}</p>
        <p class="card-text">Stock : {{pro.stock}}</p>
<!--        <p class="card-text">Available : {{pro.available}}</p>-->
<!--        -->
        {% if user.is_superuser == True %}
        {% if product.stock > 0 %}
        <h5>Product in stock</h5>
            <a href="{% url 'shop:addstock' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% else %}
        <h5>Product out of stock</h5>
            <a href="{% url 'shop:addstock' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% endif %}


        {% else %}
        {% if product.stock > 0 %}
        <a href="{% url 'cart:addtocart' pro.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center">Add to Cart</a>
        {% else %}
        <h5>Out of stock</h5>
        {% endif %}

        {% endif %}


      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .class1{
    margin:auto;
    border: 1px solid white;
    padding:20px;
    justify-content:space-around;
    align-items:center;}

</style>
<div class="class1">
    <img src="{{cat.image.url}}" height="650px" width="100%">
</div>
<div class="class1">
    <h1 class="text-center mt-0 text-secondary"><b>{{cat.name}}</b></h1>
</div>
<div class="class1">
    <p>{{cat.description}}</p>
</div>


    <div class="container-fluid">
        <div class="row">
        {% for i in pro %}
              <div class="col-md-4">
                <article class="post-item card border-1 shadow-sm p-3">
                  <div class="image-holder zoom-effect">
                    <a href="#">
                      <img src="{{i.image.url}}" alt="post" class="card-img-top" height="350px">
                    </a>
                  </div>
                  <div class="card-body text-center">
                    <div class="post-header">
                      <h3 class="post-title">{{i.name}}
                      </h3>
                        <p><i class="fa-solid fa-indian-rupee-sign"></i>{{i.price}}</p>
                        <a href="{% url 'shop:productdetails' i.id %}" class="btn btn-outline-secondary ">Details</a>
                    </div>
                  </div>
                </article>
              </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2 class="text-center mt-3">Registration</h2>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Username</label>
      <input type="text" class="form-control" name="u" placeholder="username">
    </div>

    <div class="mb-3">
    <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="password">
    </div>

    <div class="mb-3">
    <label class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="cp" placeholder="confirm password">
    </div>

    <div class="mb-3">
    <label class="form-label">First name</label>
      <input type="text" class="form-control" name="f" placeholder="first name">
    </div>

    <div class="mb-3">
    <label class="form-label">Last name</label>
      <input type="text" class="form-control" name="l" placeholder="last name">
    </div>

    <div class="mb-3">
    <label class="form-label">Email</label>
      <input type="email" class="form-control" name="e" placeholder="email">
    </div>
    <div class="mb-3">
<button type="submit" value="Register" class="form-control btn btn-outline-success">Register</button>
  </div>
</form>
{% endblock%}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if product == None %}
<form></form>
{% else %}
<h3 class="text-center">You Have Searched For {{query}}</h3>
<div class="container mt-5 p-3" style="...">
    <div class="featured-section">
		<div class="container">
			<div class="row">
                {% for i in product %}
				<div class="col-md-4">
					<div class="featured-item">
						<h5 class="card-title text-center">{{i.name}}</h5>
						<img src="{{i.image.url}}" height="200px" width="100%" alt="">
                        <h6 class="card-text"><b>price: </b>{{i.price}}</h6>
                        <div class="d-grid col-4 mx-auto">
						<a href="{% url 'shop:productdetails' i.id %}" class="btn btn-secondary btn-sm">see more</a>
                        </div></div>
				</div>

                {% empty %}
                <h2 class="text-container">No Result Found</h2>


			</div>
            {% endfor %}
		</div>
    </div>
</div>
{% endif %}
{% endblock %}